# data
training_file: data/EUR-Lex/train.txt
test_file: data/EUR-Lex/test.txt
data_name: EUR-Lex
min_vocab_freq: 1
max_seq_length: 512
include_test_labels: true
add_special_tokens: true

# train
seed: 1337
epochs: 100
batch_size: 32
optimizer: adamw
learning_rate: 0.00005
weight_decay: 0.01
patience: 10

# eval
eval_batch_size: 32
monitor_metrics: ['Micro-F1', 'RP@5']
val_metric: RP@5

# model
model_name: BERT
init_weight: null
network_config:
  dropout: 0.1
  lm_weight: bert-base-uncased
  lm_window: 512

# pretrained vocab / embeddings
embed_file: null
